/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface BlacklistResponse {
  blacklisted_addresses: string[];
  [k: string]: unknown;
}
export type Uint128 = string;
export interface Cw721DepositResponse {
  deposits: Cw721Deposit[];
  [k: string]: unknown;
}
export interface Cw721Deposit {
  ask: Coin;
  contract: string;
  owner: string;
  token_id: string;
  [k: string]: unknown;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type Cw721HookMsg = {
  deposit: {
    ask: Coin;
    [k: string]: unknown;
  };
};
export type ExecuteMsg = {
  update_admin: {
    admin: string;
    [k: string]: unknown;
  };
} | {
  receive_nft: Cw721ReceiveMsg;
} | {
  withdraw_nft: {
    contract: string;
    token_id: string;
    [k: string]: unknown;
  };
} | {
  submit_offer: {
    cw721_contract: string;
    nft_owner: string;
    token_id: string;
    [k: string]: unknown;
  };
} | {
  withdraw_offer: {
    cw721_contract: string;
    token_id: string;
    [k: string]: unknown;
  };
} | {
  add_to_blacklist: {
    address: string;
    [k: string]: unknown;
  };
} | {
  remove_from_blacklist: {
    address: string;
    [k: string]: unknown;
  };
} | {
  accept_offer: {
    bidder_address: string;
    cw721_contract: string;
    token_id: string;
    [k: string]: unknown;
  };
};
export type Binary = string;
export interface Cw721ReceiveMsg {
  msg: Binary;
  sender: string;
  token_id: string;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  admin: string;
  [k: string]: unknown;
}
export type MigrateMsg = string;
export interface NftContractsResponse {
  nft_contracts: string[];
  [k: string]: unknown;
}
export interface OfferResponse {
  offers: Offer[];
  [k: string]: unknown;
}
export interface Offer {
  amount: Coin;
  cw721_contract: string;
  owner: string;
  token_id: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  cw721_deposits: {
    address: string;
    contract: string;
    [k: string]: unknown;
  };
} | {
  offers: {
    cw721_contract: string;
    owner: string;
    [k: string]: unknown;
  };
} | {
  get_nft_contracts: {
    owner: string;
    [k: string]: unknown;
  };
} | {
  get_blacklist: {
    [k: string]: unknown;
  };
};